# Generated by Django 4.2 on 2023-05-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_profile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friend',
            new_name='follow',
        ),
    ]
