# Generated by Django 4.2 on 2023-05-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_message_delete_like_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
